00 init
WildCodeSchool/lille-js-202003-project-literate-guide-backend pull request #2
Opened 2020-06-23 14:03 UTC by llaulier

2020-06-23 14:09 UTC, RoxaneDrelon submitted a review, later dismissed
So no evill

2020-06-23 15:28 UTC, LoicBrassart requested changes
Please remove empty lines

2020-06-23 15:28 UTC, LoicBrassart commented on sql/capsule.sql
> +
... Why these empty lines ?

2020-06-23 15:28 UTC, LoicBrassart commented on sql/poi.sql
> +
Useless empty line

2020-06-29 08:01 UTC, RoxaneDrelon approved these changes
Clean indentation

2020-06-29 13:43 UTC, LoicBrassart approved these changes
SnE!

2020-06-29 13:49 UTC, merged