00 controllers
WildCodeSchool/lille-js-202003-project-literate-guide-backend pull request #3
Opened 2020-06-30 14:36 UTC by RoxaneDrelon

Added controllers, rating table sql file, rating examples, cors and minor improvements here and there.

2020-06-30 14:51 UTC, XSylvainX submitted a review, later dismissed

2020-07-06 08:02 UTC, LoicBrassart requested changes
Please remove useless dependancies

2020-07-06 08:02 UTC, LoicBrassart commented on conf.js
> +  database: process.env.DB_DATABASE, // le nom de la base de données
(These comments don't seem so useful to me, are they ?)

2020-07-06 08:02 UTC, LoicBrassart commented on package.json
> +    "mysql2": "^2.1.0"
Please remove packages you don't use anymore

2020-07-06 08:02 UTC, LoicBrassart commented on server.js
> +    console.log(`API root available on http://localhost:4242`);
`localhost:${backendPort}` ;-)

2020-07-06 08:55 UTC, XSylvainX approved these changes

2020-07-06 09:10 UTC, LoicBrassart approved these changes
SnE

2020-07-06 09:14 UTC, merged